version: '3.8'

services:
  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: always
 
  foodordering.database:
    image: postgres:15-alpine
    container_name: foodordering.database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: foodordering.dbadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
    - app_network 

  # --- REDIS CACHE ---
  foodordering.cache:
    image: redis:latest
    container_name: foodordering.cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # --- API PRESENTATION ---
  foodordering.presentation:
    image: ${DOCKER_REGISTRY-}foodorderingpresentation
    container_name: foodordering_api
    build:
      context: .
      dockerfile: FoodOrdering.Presentation/Dockerfile
    env_file:
      - .env

    depends_on:
      - "foodordering.database"
      - "foodordering.cache"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=${DefaultConnection}
      - REDIS=${REDIS}

      - API_NAME=${API_NAME}
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
      
      - SECRET_KEY=${SECRET_KEY}
      - ISSUER=${ISSUER}
      - AUDIENCE=${AUDIENCE}
      
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_ENABLE_SSL=${SMTP_ENABLE_SSL}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      
      - PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
      - PAYOS_API_KEY=${PAYOS_API_KEY}
      - PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
      - PAYOS_RETURN_URL=${PAYOS_RETURN_URL}
      - PAYOS_CANCEL_URL=${PAYOS_CANCEL_URL}
      
      - DEFAULT_AVATAR=${DEFAULT_AVATAR}
  
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:      
      - app_network 

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  pgadmin-data:
  seq_data:
